meta_product_name: "portfolio"
meta_title: "Juliette's portfolio"
meta_description: "Juliette : Product designer | Front-end developer. Création ou adaptation de vos projets Web en se focalisant sur l'expérience de vos utilisateurs."
meta_image: "social-jg.png"
twitter_account: "@turtleju"
